---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - test.example.com
  resources:
  - exampleconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - test.example.com
  resources:
  - exampleconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - test.example.com
  resources:
  - exampleconfigs/status
  verbs:
  - get
  - patch
  - update
